import type { Metadata } from "next";
import { Anek_Bangla } from "next/font/google";
import "./globals.css";
import TanStackProvider from "@/components/TanStackProvider";
import { Toaster } from "react-hot-toast";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import Navbar from "@/components/Navbar";
import { getAuthToken, getCurrentUser } from "@/lib/auth";
import { AuthProvider } from "@/components/auth-provider";

const inter = Anek_Bangla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin DashBoard Arafat Foundation",
  description: "Generated by Rakibul Hasan",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} antialiased bg-background text-foreground`}>
        {/* Navbar */}
        <TanStackProvider>
          <AuthProvider>
            {/* Navbar */}
            <Navbar />

            {/* Main Content */}
            {children}

            {/* Toast Notifications */}
            <Toaster position="top-right" />
          </AuthProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
