import type { Metadata } from "next";
import { Anek_Bangla } from "next/font/google";
import "./globals.css";
import TanStackProvider from "@/components/TanStackProvider";
import { Toaster } from "react-hot-toast";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import Navbar from "@/components/Navbar";
import { getAuthToken } from "@/lib/auth";

const inter = Anek_Bangla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin DashBoard Arafat Foundation",
  description: "Generated by Rakibul Hasan",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getAuthToken() || null;
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStackProvider>
          <NextSSRPlugin
            routerConfig={extractRouterConfig(ourFileRouter)}
          />
          <Navbar token={token} />
          {children}
          <Toaster />
        </TanStackProvider>
      </body>
    </html>
  );
}
